trigger:
  branches:
    include:
      - DBconn
pool: Default
variables:
  buildConfiguration: debug
  dotnet-version: 6.x
  debug: true
  resourceGroup: DefaultResourceGroup-WEU
  location: West Europe
  webAppName: 0ur4pp
  appServicePlanName: ASP-euroclearproject-96a5
stages:
  - stage:
    displayName: Build and Test
    jobs:
      - job: Build
        steps:
          - task: PowerShell@2
            displayName: Print all pipeline variables
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "### All pipeline variables###"
                Write-Host "Build ID"$(build.buildid)
                Write-Host "Build NR"$(build.buildnumber)
                Write-Host "buildConfiguration" $(buildConfiguration)
                Write-Host "dotnet-version" $(dotnet-version)
                Write-Host "resourceGroup" $(resourceGroup)
                Write-Host "webAppName" $(webAppName)
                Write-Host "location" $(location)
          - task: UseDotNet@2
            displayName: Install .NET SDK
            inputs:
              packageType: sdk
              version: $(dotnet-version)
          - task: DotNetCoreCLI@2
            displayName: Build projects
            inputs:
              command: 'build'
              projects: '**/*.csproj'
              arguments: '--configuration $(buildConfiguration)'
          - task: DotNetCoreCLI@2
            displayName: Publish web project
            inputs:
              command: 'publish'
              publishWebProjects: true
              arguments: >-
                --configuration $(buildConfiguration) --output
                $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            displayName: Upload site artifact
            inputs:
              PathPublish: $(Build.ArtifactStagingDirectory)
              ArtifactName: drop
              publishLocation: Container
  - stage:
    displayName: Deploy
    jobs:
      - job:
        displayName: Deploy Webapp
        steps:
          - checkout: none
          # - task: DownloadPipelineArtifact@2
          #   displayName: Download build artifactsinputs
          #   inputs:
          #     buildType: 'current'
          #     artifactName: 'drop'
          #     path: 'C:\Users\Students\Desktop\vsts-agent-win-x64-2.213.2\_work\3\s\drop'
          #  #Debugging only
          # - task: PowerShell@2
          #   condition: eq(variables.debug, ’true’)
          #   displayName: List drop files (debug)
          #   inputs:
          #     script: Get-ChildItem -Path $(Build.SourcesDirectory)\drop -recurse
          #     targetType: inline
          # - task: AzureRmWebAppDeployment@4
          #   inputs:
          #     ConnectionType: 'AzureRM'
          #     azureSubscription: 'Azure Pass - Sponsorship (fc64864b-7f89-4712-b7a8-9f1843813ade)'
          #     appType: 'webApp'
          #     WebAppName: '$(webAppName)'
          #     packageForLinux: 'C:\Users\Students\Desktop\vsts-agent-win-x64-2.213.2\_work\3\s\drop\*.zip'
          - task: DownloadPipelineArtifact@2
            displayName: Download build artifactsinputs
            inputs:
              buildType: 'current'
              artifactName: 'drop'
              path: '$(System.DefaultWorkingDirectory)'
          - task: PowerShell@2
            displayName: List drop files (debug)
            inputs:
              script: Get-ChildItem -Path $(System.DefaultWorkingDirectory)/drop -recurse
              targetType: inline
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: 0ur4pp'
            inputs:
              azureSubscription: 'SC_EC'
              WebAppName: 0ur4pp
              packageForLinux: '$(System.DefaultWorkingDirectory)/drop/*.zip'